### YamlMime:ManagedReference
items:
- uid: System.Windows.IApplicationService
  commentId: T:System.Windows.IApplicationService
  id: IApplicationService
  parent: System.Windows
  children:
  - System.Windows.IApplicationService.StartService(System.Windows.ApplicationServiceContext)
  - System.Windows.IApplicationService.StopService
  langs:
  - csharp
  - vb
  name: IApplicationService
  nameWithType: IApplicationService
  fullName: System.Windows.IApplicationService
  type: Interface
  source:
    id: IApplicationService
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\IApplicationService.cs
    startLine: 23
  assemblies:
  - OpenSilver
  namespace: System.Windows
  summary: "\nDefines methods that application extension services must implement in order to\nenable an application to start and stop the service.\n"
  example: []
  syntax:
    content: public interface IApplicationService
    content.vb: Public Interface IApplicationService
  extensionMethods:
  - System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: System.Windows.IApplicationService.StartService(System.Windows.ApplicationServiceContext)
  commentId: M:System.Windows.IApplicationService.StartService(System.Windows.ApplicationServiceContext)
  id: StartService(System.Windows.ApplicationServiceContext)
  parent: System.Windows.IApplicationService
  langs:
  - csharp
  - vb
  name: StartService(ApplicationServiceContext)
  nameWithType: IApplicationService.StartService(ApplicationServiceContext)
  fullName: System.Windows.IApplicationService.StartService(System.Windows.ApplicationServiceContext)
  type: Method
  source:
    id: StartService
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\IApplicationService.cs
    startLine: 31
  assemblies:
  - OpenSilver
  namespace: System.Windows
  summary: "\nCalled by an application in order to initialize the application extension service.\n"
  example: []
  syntax:
    content: void StartService(ApplicationServiceContext context)
    parameters:
    - id: context
      type: System.Windows.ApplicationServiceContext
      description: "\nProvides information about the application state.\n"
    content.vb: Sub StartService(context As ApplicationServiceContext)
  overload: System.Windows.IApplicationService.StartService*
- uid: System.Windows.IApplicationService.StopService
  commentId: M:System.Windows.IApplicationService.StopService
  id: StopService
  parent: System.Windows.IApplicationService
  langs:
  - csharp
  - vb
  name: StopService()
  nameWithType: IApplicationService.StopService()
  fullName: System.Windows.IApplicationService.StopService()
  type: Method
  source:
    id: StopService
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\IApplicationService.cs
    startLine: 36
  assemblies:
  - OpenSilver
  namespace: System.Windows
  summary: "\nCalled by an application in order to stop the application extension service.\n"
  example: []
  syntax:
    content: void StopService()
    content.vb: Sub StopService
  overload: System.Windows.IApplicationService.StopService*
references:
- uid: System.Windows
  commentId: N:System.Windows
  name: System.Windows
  nameWithType: System.Windows
  fullName: System.Windows
- uid: System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  parent: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  definition: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  name: ToJavaScriptObject()
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject()
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject()
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  isExternal: true
  name: ToJavaScriptObject(Object)
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject(Object)
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  commentId: T:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  parent: ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
- uid: ToJavaScriptObjectExtender
  commentId: N:ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender
- uid: System.Windows.IApplicationService.StartService*
  commentId: Overload:System.Windows.IApplicationService.StartService
  name: StartService
  nameWithType: IApplicationService.StartService
  fullName: System.Windows.IApplicationService.StartService
- uid: System.Windows.ApplicationServiceContext
  commentId: T:System.Windows.ApplicationServiceContext
  parent: System.Windows
  name: ApplicationServiceContext
  nameWithType: ApplicationServiceContext
  fullName: System.Windows.ApplicationServiceContext
- uid: System.Windows.IApplicationService.StopService*
  commentId: Overload:System.Windows.IApplicationService.StopService
  name: StopService
  nameWithType: IApplicationService.StopService
  fullName: System.Windows.IApplicationService.StopService
