### YamlMime:ManagedReference
items:
- uid: System.Windows.Automation
  commentId: N:System.Windows.Automation
  id: System.Windows.Automation
  children:
  - System.Windows.Automation.AutomationElementIdentifiers
  - System.Windows.Automation.AutomationProperties
  - System.Windows.Automation.AutomationProperty
  - System.Windows.Automation.DockPosition
  - System.Windows.Automation.ElementNotAvailableException
  - System.Windows.Automation.ElementNotEnabledException
  - System.Windows.Automation.ExpandCollapsePatternIdentifiers
  - System.Windows.Automation.ExpandCollapseState
  - System.Windows.Automation.MultipleViewPatternIdentifiers
  - System.Windows.Automation.RangeValuePatternIdentifiers
  - System.Windows.Automation.RowOrColumnMajor
  - System.Windows.Automation.ScrollAmount
  - System.Windows.Automation.ScrollPatternIdentifiers
  - System.Windows.Automation.SelectionItemPatternIdentifiers
  - System.Windows.Automation.SelectionPatternIdentifiers
  - System.Windows.Automation.SupportedTextSelection
  - System.Windows.Automation.TableItemPatternIdentifiers
  - System.Windows.Automation.TablePatternIdentifiers
  - System.Windows.Automation.ToggleState
  - System.Windows.Automation.ValuePatternIdentifiers
  - System.Windows.Automation.WindowInteractionState
  - System.Windows.Automation.WindowPatternIdentifiers
  - System.Windows.Automation.WindowVisualState
  langs:
  - csharp
  - vb
  name: System.Windows.Automation
  nameWithType: System.Windows.Automation
  fullName: System.Windows.Automation
  type: Namespace
  assemblies:
  - OpenSilver
references:
- uid: System.Windows.Automation.DockPosition
  commentId: T:System.Windows.Automation.DockPosition
  parent: System.Windows.Automation
  name: DockPosition
  nameWithType: DockPosition
  fullName: System.Windows.Automation.DockPosition
- uid: System.Windows.Automation.ElementNotAvailableException
  commentId: T:System.Windows.Automation.ElementNotAvailableException
  name: ElementNotAvailableException
  nameWithType: ElementNotAvailableException
  fullName: System.Windows.Automation.ElementNotAvailableException
- uid: System.Windows.Automation.MultipleViewPatternIdentifiers
  commentId: T:System.Windows.Automation.MultipleViewPatternIdentifiers
  name: MultipleViewPatternIdentifiers
  nameWithType: MultipleViewPatternIdentifiers
  fullName: System.Windows.Automation.MultipleViewPatternIdentifiers
- uid: System.Windows.Automation.TableItemPatternIdentifiers
  commentId: T:System.Windows.Automation.TableItemPatternIdentifiers
  name: TableItemPatternIdentifiers
  nameWithType: TableItemPatternIdentifiers
  fullName: System.Windows.Automation.TableItemPatternIdentifiers
- uid: System.Windows.Automation.TablePatternIdentifiers
  commentId: T:System.Windows.Automation.TablePatternIdentifiers
  name: TablePatternIdentifiers
  nameWithType: TablePatternIdentifiers
  fullName: System.Windows.Automation.TablePatternIdentifiers
- uid: System.Windows.Automation.AutomationElementIdentifiers
  commentId: T:System.Windows.Automation.AutomationElementIdentifiers
  name: AutomationElementIdentifiers
  nameWithType: AutomationElementIdentifiers
  fullName: System.Windows.Automation.AutomationElementIdentifiers
- uid: System.Windows.Automation.AutomationProperties
  commentId: T:System.Windows.Automation.AutomationProperties
  name: AutomationProperties
  nameWithType: AutomationProperties
  fullName: System.Windows.Automation.AutomationProperties
- uid: System.Windows.Automation.AutomationProperty
  commentId: T:System.Windows.Automation.AutomationProperty
  parent: System.Windows.Automation
  name: AutomationProperty
  nameWithType: AutomationProperty
  fullName: System.Windows.Automation.AutomationProperty
- uid: System.Windows.Automation.ElementNotEnabledException
  commentId: T:System.Windows.Automation.ElementNotEnabledException
  name: ElementNotEnabledException
  nameWithType: ElementNotEnabledException
  fullName: System.Windows.Automation.ElementNotEnabledException
- uid: System.Windows.Automation.ExpandCollapsePatternIdentifiers
  commentId: T:System.Windows.Automation.ExpandCollapsePatternIdentifiers
  name: ExpandCollapsePatternIdentifiers
  nameWithType: ExpandCollapsePatternIdentifiers
  fullName: System.Windows.Automation.ExpandCollapsePatternIdentifiers
- uid: System.Windows.Automation.ExpandCollapseState
  commentId: T:System.Windows.Automation.ExpandCollapseState
  parent: System.Windows.Automation
  name: ExpandCollapseState
  nameWithType: ExpandCollapseState
  fullName: System.Windows.Automation.ExpandCollapseState
- uid: System.Windows.Automation.RangeValuePatternIdentifiers
  commentId: T:System.Windows.Automation.RangeValuePatternIdentifiers
  name: RangeValuePatternIdentifiers
  nameWithType: RangeValuePatternIdentifiers
  fullName: System.Windows.Automation.RangeValuePatternIdentifiers
- uid: System.Windows.Automation.RowOrColumnMajor
  commentId: T:System.Windows.Automation.RowOrColumnMajor
  parent: System.Windows.Automation
  name: RowOrColumnMajor
  nameWithType: RowOrColumnMajor
  fullName: System.Windows.Automation.RowOrColumnMajor
- uid: System.Windows.Automation.ScrollAmount
  commentId: T:System.Windows.Automation.ScrollAmount
  parent: System.Windows.Automation
  name: ScrollAmount
  nameWithType: ScrollAmount
  fullName: System.Windows.Automation.ScrollAmount
- uid: System.Windows.Automation.ScrollPatternIdentifiers
  commentId: T:System.Windows.Automation.ScrollPatternIdentifiers
  name: ScrollPatternIdentifiers
  nameWithType: ScrollPatternIdentifiers
  fullName: System.Windows.Automation.ScrollPatternIdentifiers
- uid: System.Windows.Automation.SelectionItemPatternIdentifiers
  commentId: T:System.Windows.Automation.SelectionItemPatternIdentifiers
  name: SelectionItemPatternIdentifiers
  nameWithType: SelectionItemPatternIdentifiers
  fullName: System.Windows.Automation.SelectionItemPatternIdentifiers
- uid: System.Windows.Automation.SelectionPatternIdentifiers
  commentId: T:System.Windows.Automation.SelectionPatternIdentifiers
  name: SelectionPatternIdentifiers
  nameWithType: SelectionPatternIdentifiers
  fullName: System.Windows.Automation.SelectionPatternIdentifiers
- uid: System.Windows.Automation.SupportedTextSelection
  commentId: T:System.Windows.Automation.SupportedTextSelection
  parent: System.Windows.Automation
  name: SupportedTextSelection
  nameWithType: SupportedTextSelection
  fullName: System.Windows.Automation.SupportedTextSelection
- uid: System.Windows.Automation.ToggleState
  commentId: T:System.Windows.Automation.ToggleState
  parent: System.Windows.Automation
  name: ToggleState
  nameWithType: ToggleState
  fullName: System.Windows.Automation.ToggleState
- uid: System.Windows.Automation.ValuePatternIdentifiers
  commentId: T:System.Windows.Automation.ValuePatternIdentifiers
  name: ValuePatternIdentifiers
  nameWithType: ValuePatternIdentifiers
  fullName: System.Windows.Automation.ValuePatternIdentifiers
- uid: System.Windows.Automation.WindowInteractionState
  commentId: T:System.Windows.Automation.WindowInteractionState
  parent: System.Windows.Automation
  name: WindowInteractionState
  nameWithType: WindowInteractionState
  fullName: System.Windows.Automation.WindowInteractionState
- uid: System.Windows.Automation.WindowPatternIdentifiers
  commentId: T:System.Windows.Automation.WindowPatternIdentifiers
  name: WindowPatternIdentifiers
  nameWithType: WindowPatternIdentifiers
  fullName: System.Windows.Automation.WindowPatternIdentifiers
- uid: System.Windows.Automation.WindowVisualState
  commentId: T:System.Windows.Automation.WindowVisualState
  parent: System.Windows.Automation
  name: WindowVisualState
  nameWithType: WindowVisualState
  fullName: System.Windows.Automation.WindowVisualState
- uid: System.Windows.Automation
  commentId: N:System.Windows.Automation
  name: System.Windows.Automation
  nameWithType: System.Windows.Automation
  fullName: System.Windows.Automation
