### YamlMime:ManagedReference
items:
- uid: System.Windows.IApplicationLifetimeAware
  commentId: T:System.Windows.IApplicationLifetimeAware
  id: IApplicationLifetimeAware
  parent: System.Windows
  children:
  - System.Windows.IApplicationLifetimeAware.Exited
  - System.Windows.IApplicationLifetimeAware.Exiting
  - System.Windows.IApplicationLifetimeAware.Started
  - System.Windows.IApplicationLifetimeAware.Starting
  langs:
  - csharp
  - vb
  name: IApplicationLifetimeAware
  nameWithType: IApplicationLifetimeAware
  fullName: System.Windows.IApplicationLifetimeAware
  type: Interface
  source:
    id: IApplicationLifetimeAware
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationLifetimeAware.cs
    startLine: 10
  assemblies:
  - OpenSilver
  namespace: System.Windows
  syntax:
    content: public interface IApplicationLifetimeAware
    content.vb: Public Interface IApplicationLifetimeAware
  extensionMethods:
  - System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: System.Windows.IApplicationLifetimeAware.Exited
  commentId: M:System.Windows.IApplicationLifetimeAware.Exited
  id: Exited
  parent: System.Windows.IApplicationLifetimeAware
  langs:
  - csharp
  - vb
  name: Exited()
  nameWithType: IApplicationLifetimeAware.Exited()
  fullName: System.Windows.IApplicationLifetimeAware.Exited()
  type: Method
  source:
    id: Exited
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationLifetimeAware.cs
    startLine: 16
  assemblies:
  - OpenSilver
  namespace: System.Windows
  syntax:
    content: void Exited()
    content.vb: Sub Exited
  overload: System.Windows.IApplicationLifetimeAware.Exited*
- uid: System.Windows.IApplicationLifetimeAware.Exiting
  commentId: M:System.Windows.IApplicationLifetimeAware.Exiting
  id: Exiting
  parent: System.Windows.IApplicationLifetimeAware
  langs:
  - csharp
  - vb
  name: Exiting()
  nameWithType: IApplicationLifetimeAware.Exiting()
  fullName: System.Windows.IApplicationLifetimeAware.Exiting()
  type: Method
  source:
    id: Exiting
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationLifetimeAware.cs
    startLine: 21
  assemblies:
  - OpenSilver
  namespace: System.Windows
  syntax:
    content: void Exiting()
    content.vb: Sub Exiting
  overload: System.Windows.IApplicationLifetimeAware.Exiting*
- uid: System.Windows.IApplicationLifetimeAware.Started
  commentId: M:System.Windows.IApplicationLifetimeAware.Started
  id: Started
  parent: System.Windows.IApplicationLifetimeAware
  langs:
  - csharp
  - vb
  name: Started()
  nameWithType: IApplicationLifetimeAware.Started()
  fullName: System.Windows.IApplicationLifetimeAware.Started()
  type: Method
  source:
    id: Started
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationLifetimeAware.cs
    startLine: 26
  assemblies:
  - OpenSilver
  namespace: System.Windows
  syntax:
    content: void Started()
    content.vb: Sub Started
  overload: System.Windows.IApplicationLifetimeAware.Started*
- uid: System.Windows.IApplicationLifetimeAware.Starting
  commentId: M:System.Windows.IApplicationLifetimeAware.Starting
  id: Starting
  parent: System.Windows.IApplicationLifetimeAware
  langs:
  - csharp
  - vb
  name: Starting()
  nameWithType: IApplicationLifetimeAware.Starting()
  fullName: System.Windows.IApplicationLifetimeAware.Starting()
  type: Method
  source:
    id: Starting
    path: C:\Users\ashot\Desktop\Projects\GitHub-OpenSilver\src\Runtime\Runtime\System.Windows\WORKINPROGRESS\IApplicationLifetimeAware.cs
    startLine: 31
  assemblies:
  - OpenSilver
  namespace: System.Windows
  syntax:
    content: void Starting()
    content.vb: Sub Starting
  overload: System.Windows.IApplicationLifetimeAware.Starting*
references:
- uid: System.Windows
  commentId: N:System.Windows
  name: System.Windows
  nameWithType: System.Windows
  fullName: System.Windows
- uid: System.Object.ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  parent: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  definition: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  name: ToJavaScriptObject()
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject()
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject()
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  commentId: M:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  isExternal: true
  name: ToJavaScriptObject(Object)
  nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject(Object)
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
  spec.csharp:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject(System.Object)
    name: ToJavaScriptObject
    nameWithType: ToJavaScriptObjectExtender.ToJavaScriptObject
    fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender.ToJavaScriptObject
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  commentId: T:ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
  parent: ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender.ToJavaScriptObjectExtender
- uid: ToJavaScriptObjectExtender
  commentId: N:ToJavaScriptObjectExtender
  name: ToJavaScriptObjectExtender
  nameWithType: ToJavaScriptObjectExtender
  fullName: ToJavaScriptObjectExtender
- uid: System.Windows.IApplicationLifetimeAware.Exited*
  commentId: Overload:System.Windows.IApplicationLifetimeAware.Exited
  name: Exited
  nameWithType: IApplicationLifetimeAware.Exited
  fullName: System.Windows.IApplicationLifetimeAware.Exited
- uid: System.Windows.IApplicationLifetimeAware.Exiting*
  commentId: Overload:System.Windows.IApplicationLifetimeAware.Exiting
  name: Exiting
  nameWithType: IApplicationLifetimeAware.Exiting
  fullName: System.Windows.IApplicationLifetimeAware.Exiting
- uid: System.Windows.IApplicationLifetimeAware.Started*
  commentId: Overload:System.Windows.IApplicationLifetimeAware.Started
  name: Started
  nameWithType: IApplicationLifetimeAware.Started
  fullName: System.Windows.IApplicationLifetimeAware.Started
- uid: System.Windows.IApplicationLifetimeAware.Starting*
  commentId: Overload:System.Windows.IApplicationLifetimeAware.Starting
  name: Starting
  nameWithType: IApplicationLifetimeAware.Starting
  fullName: System.Windows.IApplicationLifetimeAware.Starting
